### ISSUE TITLE
Why do we need to `watch` in riverpod?

### ISSUE THREAD

**Issue by AAverin** [bizz84/tmdb_movie_app_riverpod#10]
Why do we need to `watch`  `dioProvider` (https://github.com/bizz84/tmdb_movie_app_riverpod/blob/5f97913891a2aaffd3b49d637d2e49f606fc7e42/lib/src/features/movies/data/movies_repository.dart#L72)
and `moviesRepositoryProvider` (https://github.com/bizz84/tmdb_movie_app_riverpod/blob/5f97913891a2aaffd3b49d637d2e49f606fc7e42/lib/src/features/movies/data/movies_repository.dart#L86)?

Both are defined as function providers so in practice should never change. Wouldn't we rather `read`?

**Comment by bizz84** [comment]
According to the official docs:

> Whenever possible, prefer using ref.watch over ref.read or ref.listen to implement a feature.
By relying on ref.watch, your application becomes both reactive and declarative, which makes it more maintainable.

Source:


https://docs-v2.riverpod.dev/docs/concepts/reading

**Comment by bizz84** [comment]
Your assumptions may change in the future, so you may as well go with the recommended guidelines.
