### ISSUE TITLE
Pagination Problem (When data is empty)

### ISSUE THREAD

**Issue by lmw4051** [bizz84/tmdb_movie_app_riverpod#15]
I found the issue about when the data coming from server is empty, it will show like the gif file below.

![unnamed](https://github.com/bizz84/tmdb_movie_app_riverpod/assets/2339402/06e54882-7720-448b-883e-067b5e6d375b)

**Comment by bizz84** [comment]
I believe this is resolved since I've retested the same search query after my changes to #16 and I don't get any errors.
