### ISSUE TITLE
How to return error or loading states for function annotated with @riverpod?

### ISSUE THREAD

**Issue by jeremiahwstan** [bizz84/tmdb_movie_app_riverpod#8]
Hi, thanks for writing the article on https://codewithandrea.com/articles/flutter-riverpod-generator/. One thing I would like to ask is how to return error or loading states for function annotated with @riverpod [1] as I saw that you were handling the different states on the presentation page [2]. I don't see the states being returned on the pub documentation of the library as well [3].

Thanks!

[1] https://github.com/bizz84/tmdb_movie_app_riverpod/blob/0863d8b7d1124bed31e991c11661de142180e80e/lib/src/features/movies/data/movies_repository.dart#L91-L142
[2]
https://github.com/bizz84/tmdb_movie_app_riverpod/blob/0863d8b7d1124bed31e991c11661de142180e80e/lib/src/features/movies/presentation/movies/movies_search_screen.dart#L53-L55
[3]
https://pub.dev/packages/riverpod_generator

**Comment by bizz84** [comment]
@jeremiahwstan if the code inside the provider body throws an exception, Riverpod will automatically set the state to an `AsyncError` that contains that exception.

If desired, you can throw your own exceptions, and the same behaviour will apply.
